"""
protrader_tools.py — ProTrader Data Sources as LangGraph Tools

Ports the ProTrader-SKILL custom data feeds into LangChain `@tool`-decorated
functions so the TauricResearch LangGraph analyst agents can natively consume them.

Data Sources:
  - Guru signals (congressional trades, 13F filings, RSS guru commentary)
  - Institutional fund ownership (SEC EDGAR)
  - Breaking news catalyst cache (news_dedup.json)
"""

import json
import os
import requests
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional
from langchain_core.tools import tool


# ─── Path helpers ──────────────────────────────────────────────────────────────
# When run as an OpenClaw skill, SKILL_ROOT points to the installed skill dir.
SKILL_ROOT = Path(os.getenv("PROTRADER_SKILL_ROOT", Path(__file__).resolve().parents[4]))
LOGS_DIR = SKILL_ROOT / "logs"
DATA_DIR = SKILL_ROOT / "data"


# ─── Tool 1: Guru Signals (congressional trades, 13F, RSS) ────────────────────
@tool
def get_guru_signals(ticker: str) -> str:
    """
    Look up pre-computed guru signal bonuses for a ticker.
    These are generated by the cron-based guru_tracker.py and include
    congressional STOCK Act buys, hedge fund 13F new positions, and
    GuruFocus RSS reports from top analysts (Ackman, Druckenmiller, Pelosi, etc.).
    
    Returns a JSON-formatted dictionary with guru_bonus and reason strings,
    or 'No guru signals found' if none are available.
    """
    ticker = ticker.upper().strip()
    signals_file = LOGS_DIR / "guru_signals.json"
    
    try:
        if not signals_file.exists():
            return f"No guru signals file found at {signals_file}. The guru tracker cron may not have run yet."
        
        signals = json.loads(signals_file.read_text())
        
        if ticker not in signals:
            return f"No guru signals found for {ticker}. No tracked funds, politicians, or guru RSS coverage."
        
        signal = signals[ticker]
        guru_bonus = signal.get("guru_bonus", 0.0)
        reasons = signal.get("reasons", [])
        updated = signal.get("updated", "unknown")
        
        result = {
            "ticker": ticker,
            "guru_bonus": guru_bonus,
            "reason_count": len(reasons),
            "reasons": reasons[:5],  # cap to 5 to stay within token budget
            "updated": updated,
            "signal_strength": "STRONG" if guru_bonus >= 0.7 else "MODERATE" if guru_bonus >= 0.4 else "WEAK"
        }
        return json.dumps(result, indent=2)
        
    except Exception as e:
        return f"Error reading guru signals for {ticker}: {str(e)}"


# ─── Tool 2: Breaking News Catalyst Cache ─────────────────────────────────────
@tool
def get_breaking_news_catalysts(ticker: str) -> str:
    """
    Check the breaking news dedup cache for recent high-priority news catalysts
    affecting a given ticker. Returns Tier 1 (market-moving: war, Fed, Hormuz)
    and Tier 2 (earnings, M&A, FDA) events from the last 4 hours.
    
    The cache is maintained by the standalone `breaking_news_monitor.py` script
    which scans 20 RSS feeds and Finnhub every 2 minutes.
    """
    dedup_file = LOGS_DIR / "news_dedup.json"
    ticker = ticker.upper().strip()
    
    try:
        if not dedup_file.exists():
            return f"No breaking news cache found. The news monitor may not be running."
        
        cache = json.loads(dedup_file.read_text())
        news_items = cache if isinstance(cache, list) else cache.get("items", [])
        
        cutoff_ts = (datetime.now(timezone.utc) - timedelta(hours=4)).timestamp()
        relevant = []
        
        for item in news_items:
            ts = item.get("timestamp", 0)
            if not isinstance(ts, (int, float)) or ts < cutoff_ts:
                continue
            
            # Include if macro (Tier 1/2) or specifically mentions ticker
            tier = item.get("tier", 3)
            title = item.get("title", "")
            
            if tier <= 2 or ticker in title.upper():
                relevant.append({
                    "tier": tier,
                    "title": title[:150],
                    "source": item.get("source", "unknown"),
                    "timestamp": datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%H:%M UTC")
                })
        
        if not relevant:
            return f"No Tier 1 or Tier 2 breaking news in the last 4 hours affecting {ticker}."
        
        relevant.sort(key=lambda x: x["tier"])
        return json.dumps({"ticker": ticker, "catalysts": relevant[:10]}, indent=2)
        
    except Exception as e:
        return f"Error reading breaking news cache for {ticker}: {str(e)}"


# ─── Tool 3: SEC EDGAR Hedge Fund Ownership ───────────────────────────────────
TRACKED_FUNDS = {
    "Berkshire Hathaway": "0001067983",
    "Citadel Advisors":   "0001423689",
    "Renaissance Technologies": "0001037389",
    "Bridgewater Associates":  "0001350694",
    "Tiger Global Management": "0001167483",
    "Viking Global Investors":  "0001103804",
}

_SEC_HEADERS = {
    "User-Agent": "TauricResearch-Skill research@trading.ai",
    "Accept-Encoding": "gzip, deflate",
    "Host": "data.sec.gov"
}

@tool
def get_institutional_ownership(ticker: str) -> str:
    """
    Query SEC EDGAR 13F filings to determine which major hedge funds hold a
    given stock. Returns fund names, share counts, and an overall institutional
    consensus (bullish/neutral/bearish) based on the number of tracked funds holding.
    
    Data source: SEC EDGAR (quarterly 13F filings, 24h cache).
    """
    ticker = ticker.upper().strip()
    
    try:
        funds_holding = []
        
        for fund_name, cik in TRACKED_FUNDS.items():
            try:
                url = f"https://data.sec.gov/submissions/CIK{cik.zfill(10)}.json"
                r = requests.get(url, headers=_SEC_HEADERS, timeout=10)
                if not r.ok:
                    continue
                    
                data = r.json()
                filings = data.get("filings", {}).get("recent", {})
                forms = filings.get("form", [])
                accessions = filings.get("accessionNumber", [])
                
                # Find the most recent 13F accession number
                accession = None
                for form, acc in zip(forms, accessions):
                    if "13F" in form:
                        accession = acc.replace("-", "")
                        break
                        
                if not accession:
                    continue
                    
                idx_url = f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{accession}/{accession}-index.json"
                headers_www = {**_SEC_HEADERS, "Host": "www.sec.gov"}
                idx_r = requests.get(idx_url, headers=headers_www, timeout=10)
                if not idx_r.ok:
                    continue
                    
                idx_data = idx_r.json()
                xml_file = None
                for item in idx_data.get("directory", {}).get("item", []):
                    name = item.get("name", "")
                    if "infotable" in name.lower() or name.endswith(".xml"):
                        xml_file = name
                        break
                        
                if not xml_file:
                    continue
                    
                xml_url = f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{accession}/{xml_file}"
                xr = requests.get(xml_url, headers=headers_www, timeout=15)
                if not xr.ok:
                    continue
                    
                text = xr.text
                issuers = re.findall(r'<nameOfIssuer>(.*?)</nameOfIssuer>', text)
                shares_list = re.findall(r'<sshPrnamt>(\d+)</sshPrnamt>', text)
                
                for issuer, share_count in zip(issuers, shares_list):
                    ticker_guess = issuer.split()[0].upper().replace(".", "").replace(",", "")
                    if ticker_guess == ticker:
                        funds_holding.append({
                            "fund": fund_name,
                            "shares": int(share_count)
                        })
                        break
                        
            except Exception:
                continue
        
        count = len(funds_holding)
        consensus = "bullish" if count >= 3 else "neutral" if count >= 1 else "bearish"
        
        return json.dumps({
            "ticker": ticker,
            "institutional_consensus": consensus,
            "fund_count": count,
            "funds_holding": funds_holding
        }, indent=2)
        
    except Exception as e:
        return f"Error querying institutional ownership for {ticker}: {str(e)}"
